[project]
name = "torch-md"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tfharrelson", email = "tharrel4@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.14.0",
    "datasets>=3.0.0",
    "dscribe>=2.1.2",
    "duckdb>=1.4.4",
    "fairchem-core>=2.16.0",
    "jaxtyping>=0.3.2",
    "numpy>=2.3.2",
    "patito>=0.8.6",
    "polars>=1.38.1",
    "pyarrow>=23.0.1",
    "pydantic-settings>=2.13.1",
    "pytest>=9.0.2",
    "torch>=2.7.1",
    "tqdm>=4.67.3",
    "universal-pathlib>=0.3.10",
]

[project.scripts]
torch-md = "torch_md:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "assertpy>=1.1",
    "pyright>=1.1.408",
    "pytest>=9.0.2",
    "ruff>=0.15.5",
]
